# Port can be overridden by using -p if running development flask
#port: 5000

op5monitor:
  host: monitor.aw.oc-testbench.xyz
  user: monitor
  passwd: monitor
  metric_prefix: monitor
  # Example of custom vars that should be added as labels and how to be translated
  custom_vars:
    - env:
        label_name: environment
    - site:
        label_name: dc

logger:
  # Path and name for the log file. If not set sent to stdout
  logfile: monitor-exporter
  # Format
  # format: day
  # Log level
  #level: INFO