op5monitor:
  url: https://monitor.aw.oc-testbench.xyz
  user: monitor
  passwd: monitor
  metric_prefix: monitor
  custom_vars:
    - env:
        label_name: environment
    - site:
        label_name: dc

logger:
  # Path and name for the log file. If not set sent to stdout
  logfile: monitor-exporter
  # Format
  # format: day
  # Log level
  #level: INFO